### ISSUE TITLE
Curtain status stuck on opening or closing manually 

### ISSUE THREAD

**Issue by juacho930903** [tuya/tuya-homebridge#88] opened 2021-08-10 22:18 UTC
Hello everyone.
I appreciate the great work you are doing.

**Describe the bug** 
The position (%) of the window cover in the Home app is not synchronized with the one displayed in the Tuya app when set manually (device buttons or remote control). The status in the Home app stays loading infinitely (opening.../closing…).
 It is strange, because when a position is set from the Tuya app, it matches the one in the Home app.

**Expected behavior** 
The status/position must match both in the Tuya app and in the Home app, once it is manipulated manually (physical buttons or remote control).
I know it is not a problem that affects the operation of the device, but there are family members that only use the devices from the Tuya app for the Android system and it's annoying for everyone.

**Screenshots** 
N/A

**Device info**
TuyaOpenAPI response: {"result":{"devices":[{"active_time":1626539597,"biz_type":0,"category":"cl","create_time":1626539597,"icon":"smart/icon/ay1487598680188r2sFY/d4c1466525d6ed6a830e343197320d40.png","id":"0040836XXXXXXXXXXXXX","ip":"181.58.XX.XX","lat":"6.152012682359376","local_key":"e26dfXXXXXXXXXXX","lon":"-75.62411451340299","name":"Persiana","online":true,"owner_id":"44042653","product_id":"xl3wqazcyvolagco","product_name":"zemismart chain mortor wifi ","status":[{"code":"control","value":"stop"},{"code":"percent_control","value":100},{"code":"percent_state","value":100},{"code":"control_back","value":true},{"code":"work_state","value":"closing"},{"code":"countdown","value":"cancel"},{"code":"countdown_left","value":0},{"code":"time_total","value":17544}],"sub":false,"time_zone":"-05:00","uid":"az1624509XXXXXXXXXXX","update_time":1628568441,"uuid":"0040836XXXXXXXXXXXXXX"}],"has_more":false,"last_row_key":"4B5D5371C4291XXXXXXXXXXXXXXXXXXXX","total":1},"success":true,"t":1628620838121} path = /v1.0/iot-01/associated-users/devices

**Device functions**
TuyaOpenAPI response: {"result":[{"category":"cl","devices":["0040836XXXXXXXXXXXXX"],"functions":[{"code":"control","desc":"control","name":"control","type":"Enum","values":"{\"range\":[\"open\",\"stop\",\"close\"]}"},{"code":"percent_control","desc":"percent control","name":"percent control","type":"Integer","values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"},{"code":"control_back","desc":"control back","name":"control back","type":"Boolean","values":"{}"},{"code":"countdown","desc":"countdown","name":"countdown","type":"Enum","values":"{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}"}],"product_id":"xl3wqazcyvolagco"}],"success":true,"t":1628620838702} path = /v1.0/devices/functions

**Additional context** 
Another error I have noticed is that the position shown in the Home app, is inverted with the one reported in the Homebridge console log files. Ex: In the Home app it appears as closed when in the Tuya app and the hombridge logs it appears open.
(It should be noted that this last error can be partially solved by inverting the engine direction, but it becomes uncomfortable when manipulated from the Tuya app, because the graphs and percentages are totally opposite).
As a suggestion, it would be very useful to implement a switch in the plugin configuration, allowing to invert only the position values shown in the Home app, without altering the motor direction.

Thanks again for the support.

**Comment by Hanh94** [comment] 2021-08-12 02:29
Hi @juacho930903 , Thank you for the accurate log.
We have reviewed your question carefully.
Knowing your problem is that the percentage control on the Tuya Smart App is the opposite of the Home App.
We have fixed this issue and will release it in the next release.

**Comment by xrust83** [comment] 2021-08-12 22:29
The problem is in numerical expression multiples of 5% if you set the curtain to 50, 55, 60, etc. percent, then everything is updated and does not freeze. Depends on values that are not a multiple of 5% if you set 61, 62, 67, 59%, etc. then the homkit really loops on the position of closing or opening

P/S. Who broke forward/back in the 1.4.0 update? Take everything back. The directional setting is configured in the application. Top as bottom and bottom as top and in the homekit everything works correctly. You turned my curtains upside down, since there are no settings in the homekit, and now the curtains are open in the thuja It is closed in the homekit

**Comment by juacho930903** [comment] 2021-08-13 03:02
> El problema está en múltiplos de expresión numérica del 5% si establece la cortina en 50, 55, 60, etc. por ciento, entonces todo se actualiza y no se congela. Depende de valores que no sean un múltiplo del 5% si establece 61, 62, 67, 59%, etc., entonces el homkit realmente realiza un bucle en la posición de cierre o apertura.
> 
> PD. ¿Quién avanzó / retrocedió en la actualización 1.4.0? Recupera todo. La configuración direccional se configura en la aplicación. Arriba como abajo y abajo como arriba y en el Homekit todo funciona correctamente. Volteaste mis cortinas al revés, ya que no hay configuraciones en el homekit, y ahora las cortinas están abiertas en el thuja.Están cerradas en el homekit.

**Comment by juacho930903** [comment] 2021-08-13 03:35
@xrust83 It is almost impossible to set a percentage in multiplies of 5 manually (physical button or remote control). This was reported because in the log window of the Tuya app, it indicates the actual percentage in which the curtain is (whatever its position) and I thought it was possible to synchronize it with  Home app.

As for the other issue, I know someone else who also works correctly with the new version (Tuya app synced with Home app). Possibly there are several different devices and an interchangeable parameter should be programmed in the code (as originally suggested). 

Best regards!

**Comment by xrust83** [comment] 2021-08-13 06:56
you need to turn the curtains over Ilyinichna in the tuyasmart or lifesmart application.  and if they are displayed correctly, then they are displayed correctly in the homekit.  if the motor is on the left then the mode is back; if the motor is on the right then the mode is forward.  in back mode, when setting the curtain in the lower position, the upper one is remembered, and when setting the upper one, the lower one.  and everything works and displays correctly.  I think someone did not figure it out and created a problem that you turned over in the code.  but it was not necessary at all to deal with the native application.


As for the percentages, I do not use the remote control or manually I ask Siri in HomePod mini to open a window for a specific one.  I think someone wrote in the code after 5% by analogy with the dimer so that the code was smaller.  if you write in increments of 1% of the lines will be 100 and not 20, but it will work more stable.  but that's just my guess

**Comment by mhunt407** [comment] 2021-08-13 13:26
I'm so pleased to have my curtains in homekit, but I have the same issue. It gets stuck on opening / closing inside homekit.

**Comment by Hanh94** [comment] 2021-08-16 09:25
Hi @juacho930903, @xrust83 , @mhunt407 , Sorry for the late reply.

We determine whether 0 is on or off by the direction of the motor. If the motor control_back_mode of the device is back or opposite and control_back is true, then 0% of the Tuya Smart panel is on. In order to keep the Home App consistent with the panel on the Tuya Smart, we use the (100-X) algorithm, if the motor is normal, then use the original value.

@xrust83  Regarding dp "position" control, Tuya requires that minstep be 5, if you control through the Home App, whether the real device behaves properly or just the Home App status update is incorrect.

@xrust83 @mhunt407 , Please provide the corresponding log of device information according to the issue template.

**Comment by mhunt407** [comment] 2021-08-16 09:52
Hey @Hanh94 - I hope this helps. Also, my curtains are the correct way in Tuya app (with no option to change direction or anything) but the opposite way in Homekit. So when homekit shows closed, they're open and when homekit shows "opening" they're actually closed.

Here's the log when they get stuck on "opening": 

TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/iot-03/open-hub/access-config, params = null, body = {"uid":"eu161203377XXXXXXX","link_id":"61dbe890-fe76-11eb-87c8-XXXXXXX","link_type":"mqtt","topics":"device","msg_encrypted_version":"1.0"}, headers = {"t":"1629106998786","client_id":"vaxgnhemau2lmsl8ak3q","nonce":"61c50530-fe76-11eb-87c8-6XXXXXXX","Signature-Headers":"client_id","sign":"946CB8AE75E761C158DC5B0585D04FDAD02397XXXXXX","sign_method":"HMAC-SHA256","access_token":"cdd5bd2XXXXXXXXX","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.4.0"}

TuyaOpenAPI response:
 {"result":{"client_id":"cloud_db42f2aaecaa055fdbaeeb4ae33b50a0","expire_time":7200,"password":"303fbdc2aa2ea61abc5f63c814f21d7e","sink_topic":{"device":"cloud/token/out/{device_id}"},"source_topic":{"device":"cloud/token/in/68a929c23595fc12f5568bf825036ae6"},"url":"ssl://m1.tuyaeu.com:8883","username":"cloud_68a929c23595fc12f5568bf825036ae6"},"success":true,"t":1629107000008} path = /v1.0/iot-03/open-hub/access-config
TuyaOpenMQ connecting: ssl://m1.tuyaeu.com:8883
TuyaOpenMQ connected
TuyaOpenAPI request: method = post, endpoint = https://openapi.tuyaeu.com, path = /v1.0/devices/bff1c134ad59c498d8o17h/commands, params = null, body = {"commands":[{"code":"percent_control","value":100}]}, headers = {"t":"1629107158700","client_id":"vaxgnhemau2lmsl8ak3q","nonce":"61c50530-fe76-11eb-87c8-6bb840b26b17","Signature-Headers":"client_id","sign":"1CA6CA5D753CBB43C89EAFB6276115892B687E05F36A908805050FEAC44150E4","sign_method":"HMAC-SHA256","access_token":"cdd5bd2a4525d240e730bd285bafda9a","lang":"en","dev_lang":"javascript","dev_channel":"homebridge","devVersion":"1.4.0"}

TuyaOpenAPI response: 
{"result":true,"success":true,"t":1629107159883} path = /v1.0/devices/bff1c134ad59c498d8o17h/commands
TuyaOpenMQ onMessage: topic = cloud/token/in/68a929c23XXXXXXX, message = {"data":{"dataId":"8f1c4db0-693a-4bcc-ab26-0XXXXXXX","devId":"bff1c134adXXXXXX","productKey":"lcvgietqregooxab","status":[{"2":100,"code":"percent_control","t":"1629107158","value":100}]},"protocol":4,"pv":"2.0","sign":"d56c9756774b8ec187b83cddXXXXXX","t":162XXXXXX}
TuyaOpenMQ onMessage: topic = cloud/token/in/68a929c23595fc12f55XXXXXXXX, message = {"data":{"dataId":"e3a234d0-6ea4-496c-9c74-9910552e9f1d","devId":"bff1c134XXXXXX","productKey":"lcvgietqregooxab","status":[{"7":"closing","code":"work_state","t":"1629107159","value":"closing"}]},"protocol":4,"pv":"2.0","sign":"f4797f040b3af7ba48334eXXXX","t":1629XXXX}

**Comment by Hanh94** [comment] 2021-08-16 11:43
> @xrust83 It is almost impossible to set a percentage in multiplies of 5 manually (physical button or remote control). This was reported because in the log window of the Tuya app, it indicates the actual percentage in which the curtain is (whatever its position) and I thought it was possible to synchronize it with Home app.
> 
> As for the other issue, I know someone else who also works correctly with the new version (Tuya app synced with Home app). Possibly there are several different devices and an interchangeable parameter should be programmed in the code (as originally suggested).
> 
> Best regards!

Hi @juacho930903 , Has the latest version 1.4.0, solved your problem? look forward to your feedback.

**Comment by juacho930903** [comment] 2021-08-16 16:32
Hi @Hanh94,  the latest update partially solved the problem. In order for the position in the Home app to be reported properly, I have to reverse the motor direction from the Tuya app while restarting the plugin in Homebridge; once loaded, the motor direction has to be reversed again in the Tuya app. This is the only way to synchronize the two apps correctly.

As for the other problem, it still locks the position in the Home app when set from the physical buttons or the remote control.  

Thanks again to the team for their work.

**Comment by jonas240** [comment] 2021-08-17 18:37
@juacho930903 Thank you for that work around! It worked temporary for me. However, @Hanh94 if you would be able to fix that permanently without that "work around" that would be amazing! It's quite annoying to change settings in the tuya smart app every time I restart or update the tuya bridge.

Regarding the "...closing" issue. I can tell in 1.4.0 I still got the problem. While "...opening" transitions to "open" like it should, "...closing" on the other hand never transitions to closed. Further, I get this log, but I am not sure if there is a direct correlation:
`[Tuya Platform Bridge 8994@Target Position] The write handler for the characteristic 'Target Position' on the accessory 'zemismart chain mortor wifi ' was slow to respond!`


My device:

`
{"devices":[{"active_time":1611254080,"biz_type":0,"category":"cl","create_time":1611254080,"icon":"smart/icon/ay1487598680188r2sFY/d4c1466525d6ed6a830e343197320d40.png","id":"3201103698f4abf02121","ip":"XX.XXX.XXX.XXX","lat":"XXXXXXX","local_key":"XXXXXXXXXXXXX","lon":"XXXXXXXX","name":"zemismart chain mortor wifi ","online":true,"owner_id":"2449XXXX","product_id":"xl3wqazcyvolagco","product_name":"zemismart chain mortor wifi ","status":[{"code":"control","value":"open"},{"code":"percent_control","value":0},{"code":"percent_state","value":0},{"code":"control_back","value":false},{"code":"work_state","value":"opening"},{"code":"countdown","value":"cancel"},{"code":"countdown_left","value":0},{"code":"time_total","value":19040}],"sub":false,"time_zone":"+01:00","uid":"eu161125371392XXXXXX","update_time":1628931872,"uuid":"3201103698f4abXXXXXX"}],"has_more":false,"last_row_key":"FB5C5FA7F3085886C28A464FEXXXXXXX","total":1},"success":true,"t":1629223299977} path = /v1.0/iot-01/associated-users/devices 
`

``
{"result":[{"category":"cl","devices":["3201103698f4abf02121"],"functions":[{"code":"control","desc":"control","name":"control","type":"Enum","values":"{\"range\":[\"open\",\"stop\",\"close\"]}"},{"code":"percent_control","desc":"percent control","name":"percent control","type":"Integer","values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"},{"code":"control_back","desc":"control back","name":"control back","type":"Boolean","values":"{}"},{"code":"countdown","desc":"countdown","name":"countdown","type":"Enum","values":"{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}"}],"product_id":"xl3wqazcyvolagco"}],"success":true,"t":1629223300141} path = /v1.0/devices/functions
``

Best regards Jonas

**Comment by xrust83** [comment] 2021-08-29 19:50
> We determine whether 0 is on or off by the direction of the motor. If the motor control_back_mode of the device is back or opposite and control_back is true, then 0% of the Tuya Smart panel is on. In order to keep the Home App consistent with the panel on the Tuya Smart, we use the (100-X) algorithm, if the motor is normal, then use the original value.

I think this is the problem. If the control_back_mode mode is enabled in the Lifestart application, then the application already sends the correct position of the curtains to the homekit. And if you transfer the position from the motor, then flip it over again.
The physical position of the motor is 90% - the control_back_mode is on and Lifesmart sent the 10% position, you defined the control_back_mode and programmatically turned it over again by 90%. And if the control_forward_mode is enabled, then everything works as it should 10% thuja is also 10% and does not flip.
If the user has a motor behind the curtain and works correctly, then they did not notice this problem. If the motor on the right is inverted. In my case, there are 2 curtains in the kitchen and a motor on the old one on the right to the second on the left and the curtains on the 1.4.0 version go in different directions. But on version 1,3,1 everything is perfect

**Comment by Hanh94** [comment] 2021-08-31 02:47
Hi guys, Sorry for the late reply And Thank you for your feedback.
We have carefully analyzed your problem and dealt with it accordingly.

1. According to the dp code of the **"situation_set"** of the device, can judge whether 100% is fully open or fully close. By default, 100% means fully close and 0% means fully open, which can solve the problem of keeping state synchronization between Tuya Smart App and Home App.
2. As for the curtain status on the Home App, it is always displayed as closing or opening, so we adapt new and old devices. We guarantee that the device after the end of execution, return to the final state can be set to **Characteristic.CurrentPosition**, enables the state of the Home App to correct.

We will be releasing this update shortly And Thanks again.

**Comment by xrust83** [comment] 2021-09-23 21:42
> Hi @juacho930903, @xrust83 , @mhunt407 , Sorry for the late reply.
> 
> We determine whether 0 is on or off by the direction of the motor. If the motor control_back_mode of the device is back or opposite and control_back is true, then 0% of the Tuya Smart panel is on. In order to keep the Home App consistent with the panel on the Tuya Smart, we use the (100-X) algorithm, if the motor is normal, then use the original value.
> 
> @xrust83 Regarding dp "position" control, Tuya requires that minstep be 5, if you control through the Home App, whether the real device behaves properly or just the Home App status update is incorrect.
> 
> @xrust83 @mhunt407 , Please provide the corresponding log of device information according to the issue template.

I checked the step on the plugin version 1.3.1 it becomes 10% if you ask siri open 75% of the curtains they will open by 80% if 85 then respectively 90%

**Comment by Hanh94** [comment] 2021-11-04 03:11
Hi guys, sorry for the late reply.
Please see https://github.com/tuya/tuya-homebridge/issues/102#issuecomment-958782460

**Closed** 2021-12-15 08:00 UTC
Labels: bug, released
